// lit/src/autocomplete-input.ts
import { html, LitElement } from "lit";
import { customElement, state } from "lit/decorators.js";

interface IResult {
  id: number;
  title: string;
  body: string;
  userId: number;
}

@customElement("autocomplete-input")
export class AutocompleteInput extends LitElement {
  @state()
  query: string = "";

  @state()
  results: IResult[] = [];

  BASE_URL: string = "https://jsonplaceholder.typicode.com/posts";

  async onSearch(e) {
    this.query = e.target.value;

    const data = await fetch(this.BASE_URL)
      .then((res) => res.json())
      .catch((err) => {
        console.log("Error Fetching Data ", err);
      });

    this.results = data.filter((item) => item.title.includes(this.query));
  }

  render() {
    return html` <div>
      <input
        type="text"
        value=${this.query}
        @input=${(e) => this.onSearch(e)}
      />
      <div>
        ${this.results.map(
          (result) => html`
            <div>
              <a href=${this.BASE_URL + "/" + result.id}>${result.title}</a>
            </div>
          `
        )}
      </div>
    </div>`;
  }
}

// svelte/src/lib/AutoCompleteInput.svelte
<script lang="ts">
  interface IResult {
    id: number;
    title: string;
    body: string;
    userId: number;
  }

  const BASE_URL = "https://jsonplaceholder.typicode.com/posts";

  let query: string = "";
  let results: IResult[] = [];
  const fetchData = async () => {
    const data = await fetch(BASE_URL)
      .then((res) => res.json())
      .catch((err) => {
        console.log("Error Fetching Data ", err);
      });
    results = data.filter((item) => item.title.includes(query));
  };
</script>

<div>
  <input
    type="text"
    bind:value={query}
    on:input={fetchData}
    placeholder="Type Your Search Here"
  />
  <div>
    {#each results as result}
      <div>
        <a href={`${BASE_URL}/${result.id}`} target="_blank">{result.title}</a>
      </div>
    {/each}
  </div>
</div>
