// angular/src/app/components/like-dislike/like-dislike.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'like-dislike',
  template: `
    <div>
      <button
        class="like-button"
        [class.liked]="liked"
        (click)="onLikeBtnClicked()"
      >
        Likes |
        <span class="likes-counter"> {{ countLikes }} </span>
      </button>
      <button
        class="dislike-button"
        [class.disliked]="disliked"
        (click)="onDislikeBtnClicked()"
      >
        Dislikes |
        <span class="dislikes-counter"> {{ countDislikes }} </span>
      </button>
    </div>
  `,
  styles: [
    `
      .like-button,
      .dislike-button {
        font-size: 1rem;
        padding: 5px 10px;
        color: #585858;
      }

      .liked,
      .disliked {
        font-weight: bold;
        color: #1565c0;
      }
    `,
  ],
})
export class LikeDislikeComponent implements OnInit {
  countLikes: number = 100;
  liked: boolean = false;
  countDislikes: number = 25;
  disliked: boolean = false;

  constructor() {}

  ngOnInit(): void {}

  onLikeBtnClicked() {
    if (!this.liked) {
      this.countLikes += 1;
    } else {
      this.countLikes -= 1;
    }

    if (this.disliked) this.disliked = false;
    this.liked = !this.liked;
  }

  onDislikeBtnClicked() {
    if (!this.disliked) {
      this.countDislikes += 1;
    } else {
      this.countDislikes -= 1;
    }

    if (this.liked) this.liked = false;
    this.disliked = !this.disliked;

  }
}

// svelte/src/lib/LikeDislike.svelte
<script lang="ts">
  let countLikes: number = 100;
  let liked: boolean = false;
  let countDislikes: number = 25;
  let disliked: boolean = false;

  const onLikeBtnClicked = () => {
    countLikes += liked ? -1 : 1;
    if (disliked) {
      countDislikes -= 1;
      disliked = false;
    }
    liked = !liked;
  };

  const onDislikeBtnClicked = () => {
    countDislikes += disliked ? -1 : 1;
    if (liked) {
      countLikes -= 1;
      liked = false;
    }
    disliked = !disliked;
  };
</script>

<div>
  <button class="like-button" class:liked on:click={onLikeBtnClicked}
    >Likes | <span class="likes-counter">{countLikes}</span>
  </button>

  <button class="dislike-button" class:disliked on:click={onDislikeBtnClicked}
    >Dislikes | <span class="dislikes-counter">{countDislikes}</span>
  </button>
</div>

<style>
  .like-button,
  .dislike-button {
    font-size: 1rem;
    padding: 5px 10px;
    color: #585858;
  }

  .liked,
  .disliked {
    font-weight: bold;
    color: #1565c0;
  }
</style>
