// vue/src/components/Rating.vue
<script setup lang="ts">
interface IRatingProps {
  name: string;
  content: string;
  rate: number;
}

const props = defineProps<IRatingProps>();
</script>

<template>
  <div>
    <i
      v-for="n of 5"
      class="fa fa-star"
      :class="{ filled: n <= props.rate }"
    ></i>
  </div>
</template>

<style scoped>
.fa-star {
  color: transparent;
  -webkit-text-stroke: 1px #000;
}
.filled {
  color: black;
}
</style>

// svelte/src/lib/Rating.svelte
<script lang="ts">
  export let name: string = "";
  export let content: string = "";
  export let rate: number = 0;
</script>

<div>
  {#each Array(5) as star, index}
    <i class="fa fa-star" class:filled={index < rate} /> <!-- content here -->
  {/each}
</div>

<style>
  .fa-star {
    color: transparent;
    -webkit-text-stroke: 1px #000;
  }
  .filled {
    color: black;
  }
</style>
